# -*- coding: utf-8 -*-
"""Ev1_p5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16YOg9pDWPTI0fqT0BVGe7gN-dEwICNU-
"""

orbitals = ["1s", "2s", "2p", "3s", "3p", "4s", "3d", "4p", "5s", "4d", "5p", "6s", "4f", "5d", "6p", "7s", "5f", "6d", "7p"]
orbitalsValue = {"s": 2, "p": 6, "d": 10, "f": 14}
nombre= ""
while nombre!="Exit":
  confg= ""
  nombre= input("Ingrese el nombre del elemento: ")
  #se ponen las condiciones de terminar y de la entrada
  if nombre=="Exit":
    break
  if len(nombre)>50:
    print("El nombre del elemento no puede tener mas de 50 caracteres")
    continue
  numero= int(input("Ingrese el numero atomico: "))
  if numero==0:
    confg= "1s0"
  #se va mirando cuantos electrones del atomo "rellenan" los orbitales
  else:
    for i in range(numero):
      value = orbitalsValue[orbitals[i][1]]
      if numero==0:
        break
      elif value<=numero:
      #si los electrones son mas que los del nivel,
          confg= confg + " " + orbitals[i] + str(value)
          #entonces se pone ese nivel completo y se revisa el siguiente
          numero= numero - value
      #si los electrones no completan el nivel, hasta ahi se pone la configuracion
      elif numero < value:
          confg= confg+  " " + orbitals[i] + str(numero)
          break
  print(confg)