# -*- coding: utf-8 -*-
"""Ev1_p3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-UHKY4PTdrw7vDw16i4al8abCJxCZc4J
"""

num= 1
while num!=0:
  num = float(input("Ingrese un numero entero:"))
  #se confirma que se cumplan las condiciones del ejercicio
  if num!=int(num):
    print("El numero no es entero, por favor intente de nuevo")
  elif num>=4000:
    print("El numero es mayor que 4000, por favor intente de nuevo")
  else:
    num= int(num)
    numero_romano = ""
    #el numero se va dividiendo en unidades decenas etc
    if num >= 1000:
        m = num // 1000
        numero_romano= numero_romano + "M"*m
        num = num % 1000
    if num >= 100:
        c = num // 100
        #si la centena es 9, solo se le quita a 10
        if c == 9:
            numero_romano = numero_romano + "CM"
        #si es 5< y <9 entonces se agrega la C maximo 3 veces
        elif c >= 5:
            numero_romano = numero_romano + "D" + "C" * (c - 5)
        elif c == 4:
            numero_romano = numero_romano + "CD"
        #si es menor que 4 entonces solo se suma el C maximo 3 veces
        else:
            numero_romano = numero_romano + "C" * c
        num = num % 100
    #la forma del proceso se repite para cada parte
    if num >= 10:
        d = num // 10
        if d == 9:
            numero_romano = numero_romano + "XC"
        elif d >= 5:
            numero_romano = numero_romano + "L" + "X" * (d - 5)
        elif d == 4:
            numero_romano = numero_romano + "XL"
        else:
            numero_romano = numero_romano + "X" * d
        num = num % 10
    if num > 0:
        if num == 9:
            numero_romano = numero_romano + "IX"
        elif num >= 5:
            numero_romano = numero_romano + "V" + "I" * (num - 5)
        elif num == 4:
            numero_romano = numero_romano + "IV"
        else:
            numero_romano = numero_romano + "I" * num
    print("El numero romano es:", numero_romano)