# -*- coding: utf-8 -*-
"""Ev1_p1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EuT75AGl3g__LkgwhA7JpIjwTaqucUue
"""

import numpy as np

#se piden los datos del conjunto de datos
n= int(input("Ingrese el tamaño del vector: "))
vector= np.empty(0, dtype=int)
print("Ingrese cada uno de los valores: ")
for i in range (n):
  num= int(input(f"{i+1}."))
  vector= np.append(vector, num)
vector= np.sort(vector)
print(vector)

obj= int(input("Ingrese el numero a buscar: "))
izq= 0
der= n-1
punto = -1

while izq<=der:
  #se saca la mitad del vector
  lim= int((der+izq)/2)
  if obj==vector[lim]:
    #der= lim-1 para conseguir la primera posicion del numero (repetidos)
    punto = lim
    der = lim-1
  #si es menor al valor mitad, se revisa la 1ra mitad de la lista
  elif obj<vector[lim]:
    der= lim-1
  #de los contrario, se revisa la 2da mitad
  else:
    izq= lim+1

#si el punto quedo negativo es que no esta en el vector
if punto != -1:
  print(f"El numero {obj} se encuentra en la posicion {punto+1}")
else:
  print(f"El numero {obj} no se encuentra en el vector")