# -*- coding: utf-8 -*-
"""Ev2_p7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1go8Lqbko3XvF9CQy50965U_DoD_Pbe4a
"""

tiempo= ""
print("""A continuacion puede escoger entre los verbos a conjugar: "
SALTAR, COMER, VIVIR
Despues, escoja el tiempo verbal:
Presente(A), Perfecto simple(P), Futuro(F) o Terminar el programa(T)""")
while tiempo!= "T":
  comando= input("Ingrese el verbo y el tiempo verbal separados por un espacio:")
  #se separa la palabra con el tiempo verbal que se quiere
  palabra= comando.split()[0]
  tiempo= (comando.split()[1]).upper()
  #se deja "constante" los pronombres para cada caso
  pronombres= ["Yo", "Tu", "El", "Nosotros", "Vosotros", "Ellos"]
  if tiempo== "T":
    break
  elif palabra.upper()== "SALTAR":
    #la parte que no cambia nunca del verbo es la base
    #se guarda una lista con las terminaciones del verbo para cada tiempo y pronombre
    lista_s= {"A":["o", "as", "a", "amos", "ais", "an"],
            "P":["e", "aste", "o", "amos", "asteis", "aron"],
            "F":["are", "aras", "ara", "aremos", "areis", "aran"]}
    for i in range(6):
      # la frase conjugada es el pronombre + la base del verbo como la escribio el usuario
      # + la terminacion correspondiente
      conjugar= pronombres[i] + " " + palabra[:4] + lista_s[tiempo][i]
      print(conjugar)
  elif palabra.upper()== "COMER":
    lista_c= {"A":["o", "es", "e", "emos", "eis", "en"],
              "P":["i", "iste", "io", "imos", "isteis", "ieron"],
              "F": ["ere", "eras", "era", "eremos", "ereis", "eran"]}
    for i in range(6):
      conjugar= pronombres[i] + " " + palabra[:3] + lista_c[tiempo][i]
      print(conjugar)
  elif palabra.upper()== "VIVIR":
    lista_v= {"A":["o", "es", "e", "imos", "is", "en"],
              "P":["i", "iste", "io", "imos", "isteis", "ieron"],
              "F":["ire", "iras", "ira", "iremos", "ireis", "iran"]}
    for i in range(6):
      conjugar= pronombres[i] + " " + palabra + lista_v[tiempo][i]
      print(conjugar)
  else:
    print("Por favor escoja un verbo y/o tiempo verbal entre las opciones")
    continue
  #se borran las ultimas frases para que no se mezclen con la nueva entrada
  conjugar= ""